name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Prepare Addon Zip
        id: prepare
        run: |
          # Define variables
          PROJECT_NAME="blender-unreal-rig-utils"
          VERSION=${GITHUB_REF_NAME} # This grabs the tag (e.g., v1.0.3)
          ZIP_NAME="${PROJECT_NAME}_${VERSION}.zip"
          
          # Create the zip. 
          # We include the folder itself so it's installable in Blender.
          zip -r "$ZIP_NAME" unreal_rig_utils/ README.md LICENSE
          
          # Pass the filename to the next step
          echo "zip_path=$ZIP_NAME" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.prepare.outputs.zip_path }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true # Automatically creates a changelog
          draft: false
          prerelease: false